apiVersion: network.openshift.io/v1
kind: EgressNetworkPolicy
metadata:
  name: limit-to-good-stuff
spec:
  egress:
    - type: Allow
      to:
        dnsName: www.inventx.ch
    - type: Allow
      to:
        dnsName: idontlike.work
    - type: Deny
      to:
        cidrSelector: 0.0.0.0/0
